### PR TITLE
feat(flux-components): modify pre-existing features

### PR DESCRIPTION
**Pull request by unix-chkpwd**
\\ Made changes to the flux controller persistence for artifacts and helm charts.

\\ Added a patch for decryption and postBuild. 

\\ Enabled OOM for the flux-controller.

### CODE REVIEW

**Comment by tigattack** [comment]
LGTM :shipit:

**Comment by unix-chkpwd** [comment]
Acronyms are offensive to me. I suggest you remove it. #CrackPipeEngineer

**Comment by tigattack** [comment]
As someone without features, I'm offended by the mention of features and ask you to remove all features at once.

**Comment by ditrames** [comment]
im offended by the ignorance to new technolidgys. pls impliment in no code

**Comment by tigattack** [comment]
I'm offended by your terrible spelling, grammer, and use of punctuation. please remove yourself.

**Comment by ditrames** [comment]
im offenbed bay your ignorded to counmter spelling tackticks pls stop

**Comment by unix-chkpwd** [comment]
average crackpipe monkeys

**Pull request merged**
